version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: b2b
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

  customers-api:
    build: ./customers-api
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=b2b
      - JWT_SECRET=secret123
    depends_on:
      - mysql

  orders-api:
    build: ./orders-api
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=b2b
      - CUSTOMERS_API_BASE=http://customers-api:3001
      - SERVICE_TOKEN=internal123
      - JWT_SECRET=secret123
    depends_on:
      - mysql
      - customers-api
